name: raylib
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/HrX03/raylib5.dart

environment:
  sdk: ^3.3.0-127.0.dev

# Add regular dependencies here.
dependencies:
  collection: ^1.18.0
  ffi: ^2.1.0

dev_dependencies:
  analyzer: ^6.3.0
  args: ^2.4.2
  dart_style: ^2.3.4
  ffigen: ^10.0.0
  lint: ^2.2.0
  path: ^1.8.3
  recase: ^4.1.0
  test: ^1.24.0

ffigen:
  output: 'lib/src/generated_raylib.dart'
  headers:
    entry-points:
      - 'src/raylib.h'
  name: 'RayLibNative'